language: node_js
node_js:
  - "node"
  
after_success:
  - bash ./deploy.sh

env:
  global:
    - ENCRYPTION_LABEL: "26b4962af0e7"
    - COMMIT_AUTHOR_EMAIL: "justincyork@gmail.com"
  
notifications:
  email:
    on_success: never
    on_failure: always